import { useEffect, useState } from 'react'
import { THREAT_META } from './data.js'

// Staggered reveal: report blocks fade in sequentially when a session is selected.
function useStagedReveal(sessionId, stages, delay = 140) {
  const [stage, setStage] = useState(0)
  useEffect(() => {
    setStage(0)
    let i = 0
    const t = setInterval(() => {
      i += 1
      setStage(i)
      if (i >= stages) clearInterval(t)
    }, delay)
    return () => clearInterval(t)
  }, [sessionId, stages, delay])
  return stage
}

export default function ReasoningPanel({ session }) {
  const stage = useStagedReveal(session?.id, 5)

  if (!session) {
    return (
      <section className="card reason-card">
        <div className="reason-empty">Select a session to request agent analysis</div>
      </section>
    )
  }

  const { reasoning, level, id, score } = session
  const meta = THREAT_META[level]

  return (
    <section className="card reason-card" key={id}>
      <div className="reason-head">
        <div className="reason-title">
          <span className="reason-kicker">Agent 02 · Reasoning report</span>
          <h2>
            <span className="mono">{id}</span>
            <span className={`badge lv-badge-${level}`}>
              <span className="badge-dot" />
              {meta.label}
            </span>
            <span className="reason-score mono">conf {score.toFixed(2)}</span>
          </h2>
        </div>
        <div className="reason-action">
          <span className="reason-action-label">Disposition</span>
          <span className={`reason-action-value lv-text-${level}`}>{reasoning.action}</span>
        </div>
      </div>

      <div className="reason-body">
        <div className={`reason-block ${stage >= 1 ? 'on' : ''}`}>
          <h3>Assessment</h3>
          <p>{reasoning.opening}</p>
          <p className="reason-context">{reasoning.context}</p>
        </div>

        <div className={`reason-block ${stage >= 2 ? 'on' : ''}`}>
          <h3>Top reasons · why this was flagged</h3>
          {reasoning.indicators.length === 0 ? (
            <p className="reason-dim">No detector signals fired. Session sits inside the benign baseline envelope.</p>
          ) : (
            <ul className="indicator-list">
              {reasoning.indicators.map((ind, i) => (
                <li key={ind.key}>
                  <div className="indicator-head">
                    {ind.confidence != null ? (
                      <span className="indicator-rank">#{i + 1}</span>
                    ) : (
                      <span className="flag-chip">{ind.short}</span>
                    )}
                    <strong>{ind.label}</strong>
                    {ind.confidence != null && (
                      <span
                        className={`reason-chip ${ind.confidence >= 0.65 ? 'rc-red' : ind.confidence >= 0.45 ? 'rc-amber' : 'rc-low'}`}
                      >
                        conf <b>{ind.confidence.toFixed(2)}</b>
                      </span>
                    )}
                    {ind.detected === false && <span className="indicator-soft">below threshold</span>}
                  </div>
                  <p className="indicator-evidence">{ind.text}</p>
                  <p className="indicator-detail">{ind.detail}</p>
                </li>
              ))}
            </ul>
          )}
        </div>

        <div className={`reason-block ${stage >= 3 ? 'on' : ''}`}>
          <h3>Remediation path</h3>
          {reasoning.remediation.length === 0 ? (
            <p className="reason-dim">None required.</p>
          ) : (
            <ol className="remediation-list">
              {reasoning.remediation.map((r, i) => (
                <li key={i}>{r}</li>
              ))}
            </ol>
          )}
        </div>

        <div className={`reason-block verdict lv-border-${level} ${stage >= 4 ? 'on' : ''}`}>
          <h3>Verdict</h3>
          <p>{reasoning.verdict}</p>
        </div>
      </div>

      <div className="reason-foot">
        Report generated by fcu-adjudicator-70b · advisory only · final disposition requires analyst sign-off
      </div>
    </section>
  )
}
